<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headMeta()->appendHttpEquiv('X-UA-Compatible','IE=edge')
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendName('description', '')
                ->appendName('author', '');

          echo $this->headTitle('BoM Squad')->setSeparator(' - ')->setAutoEscape(false);
          echo $this->headScript();
          echo $this->headLink();
        ?>

        <script src="//use.typekit.net/fon5yaj.js"></script>
        <script>try{Typekit.load();}catch(e){}</script>
    </head>
    <body>
        <div class="container container-valign auth">
            <div class="container-wrapper">
                <div class="col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-4 col-lg-offset-4">
                    <?php echo $this->content; ?>
                </div>
            </div>
        </div> <!-- /container -->
        <?php
          echo $this->inlineScript()
            ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js', 'text/javacript', array('conditional' => 'lt IE 9'))
            ->prependFile($this->basePath() . '/js/ie10-viewport-bug-workaround.js', 'text/javascript', array('conditional' => 'IEMobile 10'))
            ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/js/bootstrap.min.js')
            ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.13.1/jquery.validate.min.js')
            ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.2/jquery.min.js');
        ?>
    </body>
</html>
