<h3><?php echo sprintf($this->translate('Change Password for %s'), $this->zfcUserDisplayName()); ?></h3>
<?php if ($status === true) : ?>
    <div class="alert alert-success"><?php echo $this->translate('Password changed successfully.'); ?></div>
<?php elseif ($status === false) : ?>
    <div class="alert alert-error"><?php echo $this->translate('Unable to update your password. Please try again.'); ?></div>
<?php endif; ?>

<div class="col-md-6 col-md-push-3">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <div class="bomsquad-logo"></div>
            <h2 class="panel-title"><strong><?php echo $this->translate('Reset your BoM SQUAD password') ?></strong></h2>
        </div>
        <div class="panel-body">
            <?php
            $form = $this->changePasswordForm;

            $form->prepare();
            $form->setAttribute('action', $this->url('zfcuser/changepassword'));
            $form->setAttribute('method', 'post');

            $emailElement = $form->get('identity');
            $emailElement->setValue($this->zfcUserIdentity()->getEmail());

            echo $this->form()->openTag($form);
            ?>
            <dl class="zend_form">
            <?php echo $this->formElementErrors($form->get('identity')); ?>
                <dd><?php echo $this->formInput($form->get('identity')); ?></dd>

                <dt><?php echo $this->formLabel($form->get('credential')); ?></dt>
                <dd><?php
            echo $this->formInput($form->get('credential')) . $this->formElementErrors($form->get('credential'));
            ?></dd>

                <dt><?php echo $this->formLabel($form->get('newCredential')); ?></dt>
                <dd><?php
                    echo $this->formInput($form->get('newCredential')) . $this->formElementErrors($form->get('newCredential'));
            ?></dd>

                <dt><?php echo $this->formLabel($form->get('newCredentialVerify')); ?></dt>
                <dd><?php
                    echo $this->formInput($form->get('newCredentialVerify')) . $this->formElementErrors($form->get('newCredentialVerify'));
            ?></dd>

            <?php if ($error) { ?>
                <div class="alert alert-danger alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <strong><?= $error ?></strong>
                </div>
            <?php } ?>

                <dd><?php
                    //echo $this->formInput($form->get('csrf'));
                    echo $this->formInput($form->get('submit'));
            ?></dd>

            </dl>

<?php echo $this->form()->closeTag(); ?>


        </div>
        <div class="panel-footer">
            <div class="row">
                <?php if (false && $this->enableRegistration) : ?>
                    <div class="col-md-6">
                        <a href="signup"><?php echo $this->translate('No account? Sign up.') ?></a>
                    </div>
                <?php endif; ?>
                <?php if ($this->enableRegistration) : ?>
                    <div class="col-md-6">
                        <a href="http://bomsquad.io/beta"><?php echo $this->translate('No account? Get invited.') ?></a>
                    </div>
                <?php endif; ?>
                <div class="col-md-6 text-right"><a href="signin"><?php echo $this->translate('I remember! Sign in.')?></a></div>
            </div>
        </div>
    </div>
</div>
