<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');

//Format errors
$error = "";
$error .= $this->formElementErrors()
        ->setMessageOpenFormat('<strong>')
        ->setMessageSeparatorString('</strong><br/><strong>')
        ->setMessageCloseString('</strong>')
        ->render($form->get('identity'));
?>
<div class="signin">
    <header class="simple-header">
        <div class="logo"></div>
    </header>
    <div class="panel panel-primary">
        <div class="panel-body">
            <?php echo $this->form()->openTag($form) ?>

            <div class="form-group">
                <?php echo $this->formLabel($form->get('identity')) ?>
                <div class="col-md-10">
                    <?php echo $this->formInput($form->get('identity')) ?>
                </div>
            </div>

            <div class="form-group">
                <?php echo $this->formLabel($form->get('credential')) ?>
                <div class="col-md-10">
                    <?php echo $this->formInput($form->get('credential')) ?>
                </div>
            </div>

            <?php if ($this->redirect): ?>
                <input type="hidden" name="redirect" value="<?php echo $this->redirect ?>" />
            <?php endif ?>

            <?php if ($this->redirect): ?>
                <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
            <?php endif ?>

            <div class="form-group">
              <div class="col-md-10 col-md-offset-2">
                <?php echo $this->formButton($form->get('submit')) ?>
                <div class="checkbox">
                    <label>
                      <?php echo $this->formCheckbox($form->get('remember_me')) ?><span><?php echo $this->translate('Keep me signed in') ?></span>
                    </label>
                </div>
              </div>
            </div>

            <?php if ($error) { ?>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <div class="alert alert-danger alert-dismissible" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <strong><?= $error ?></strong>
                        </div>
                    </div>
                </div>
            <?php } ?>

            <?php echo $this->form()->closeTag() ?>

        </div>
        <div class="panel-footer">
            <div class="row">
                <?php if (false && $this->enableRegistration) : ?>
                    <div class="col-md-6"><a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect=' . $this->escapeUrl($this->redirect) : '') ?>">
                            <?php echo $this->translate('No account? Create one!') ?></a>
                    </div>
                <?php endif; ?>
                <?php if ($this->enableRegistration) : ?>
                    <div class="col-md-6"><a href="http://bomsquad.io/beta">
                            <?php echo $this->translate('No account? Get invited!') ?></a>
                    </div>
                <?php endif; ?>
                <div class="col-md-6 text-right">
                    <a href="<?php echo $this->url('zfcuser/forgotpassword') ?>"><?php echo $this->translate('Forgot your password?') ?></a>
                </div>
            </div>
        </div>
    </div>
</div>
