<?php
/**
 * Configuration file generated by ZF Apigility Admin
 *
 * The previous config file has been stored in application.config.old
 */
return array(
    'modules' => array(
        'Application',
        'ZF\\DevelopmentMode',
        'ZF\\Apigility',
        'ZF\\Apigility\\Provider',
        'ZF\\Apigility\\Documentation',
        'ZF\\ApiProblem',
        'ZF\\Configuration',
        'ZF\\MvcAuth',
        'ZF\\OAuth2',
        'ZF\\Hal',
        'ZF\\ContentNegotiation',
        'ZF\\ContentValidation',
        'ZF\\Rest',
        'ZF\\Rpc',
        'ZF\\Versioning',
        'DoctrineModule',
        'DoctrineORMModule',
        'DoctrineDataFixtureModule',
        'ZfcBase',
        'ZfcUser',
        'GoalioMailService',
        'GoalioForgotPassword',
        'GoalioForgotPasswordDoctrineORM',
        'GoalioRememberMe',
        'GoalioRememberMeDoctrineORM',
        'ZfcUserDoctrineORM',
        'FabuleUser',
        'FabuleUserOAuth2',
        'EdpModuleLayouts',
        'Bom',
        'API',
        'AsseticBundle',
        'Aws',
        'NewRelic',
        'BjyAuthorize',
        'SlmQueue',
        'SlmQueueSqs',
        'MonologModule',
        'ZfrPusherModule'
    ),
    'module_listener_options' => array(
        'config_glob_paths' => array(
            'config/autoload/{,*.}{global,local}.php'
        ),
        'module_paths' => array(
            './module',
            './vendor'
        ),
        // config cache and module map cache uses filesystem, which is ephemeral on heroku
        // TODO: change to use a shared permanent cache (redis? memcache?)
        'config_cache_enabled' => getenv("APPLICATION_ENV") === "production",
        'module_map_cache_enabled' => getenv("APPLICATION_ENV") === "production",
        'cache_dir' => 'data/cache/',
        'config_cache_key' => 'bom',
        'module_map_cache_key' => 'bom',
    ),
);
