<?php
$form = $this->forgotForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/forgotpassword'));
$form->setAttribute('method', 'post');

//Format errors
$error = "";
$error .= $this->formElementErrors()
        ->setMessageOpenFormat('<strong>')
        ->setMessageSeparatorString('</strong><br/><strong>')
        ->setMessageCloseString('</strong>')
        ->render($form->get('email'));
?>

<div class="forgot">
    <header class="simple-header">
        <div class="logo"></div>
        <p class="panel-title">Oh noes! You forgot your password. No worries, we'll help you reset it.</p>
    </header>
    <div class="panel panel-primary">
        <div class="panel-body">
            <?php echo $this->form()->openTag($form); ?>

            <div class="form-group">
                <?php echo $this->formLabel($form->get('email')); ?>
                <div class="col-md-10">
                    <?php echo $this->formInput($form->get('email')); ?>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-10 col-md-offset-2">
                    <?php echo $this->formButton($form->get('submit')); ?>
                </div>
            </div>

            <?php if ($error) { ?>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <div class="alert alert-danger alert-dismissible" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <strong><?= $error ?></strong>
                        </div>
                    </div>
                </div>
            <?php } ?>

            <?php echo $this->form()->closeTag() ?>

        </div>
        <div class="panel-footer">
            <div class="row">
                <div class="col-md-6">
                <?php if (false && $this->enableRegistration) : ?>
                    <a href="<?php echo $this->url('zfcuser/register') ?>"><?php echo $this->translate('No account? Create one!'); ?></a>
                <?php endif; ?>
                <?php if ($this->enableRegistration) : ?>
                    <a href="http://fabule.com/beta"><?php echo $this->translate('No account? Get invited!'); ?></a>
                <?php endif; ?>
                </div>
                <div class="col-md-6 text-right">
                    <a href="<?php echo $this->url('zfcuser/login') ?>"><?php echo $this->translate('No wait, I remembered it! Sign in.'); ?></a>
                </div>
            </div>
        </div>
    </div>
</div>
