<div class="reset-confirm">
    <header class="simple-header">
        <div class="logo"></div>
        <o><?php echo $this->translate('Your password has been changed.'); ?></p>
    </header>
    <div class="panel panel-primary">
        <div class="panel-body">
            <div class="alert alert-success alert-dismissible" role="alert">
                <?php echo $this->translate('You can now sign in using your new password.') ?>
            </div>
        </div>

        <div class="panel-footer">
            <div class="row">
                <div class="col-md-12 text-center">
                    <a href="<?php echo $this->url('zfcuser/login') ?>"><?php echo $this->translate('Sign in.'); ?></a>
                </div>
            </div>
        </div>
    </div>
</div>
