<div class="reset-confirm">
    <header class="simple-header">
        <div class="logo"></div>
    </header>
    <div class="panel panel-primary">
        <div class="panel-body">
            <div class="alert alert-success alert-dismissible" role="alert">
                <?php echo sprintf($this->translate('A message containing a reset link has been sent to your e-mail address %s.'), $this->escapeHtml($this->email)); ?>
            </div>
        </div>
        <div class="panel-footer">
            <div class="row">
                <div class="col-md-6">
                <?php if (false && $this->enableRegistration) : ?>
                    <a href="<?php echo $this->url('zfcuser/register') ?>"><?php echo $this->translate('No account? Sign up.'); ?></a>
                <?php endif; ?>
                <?php if ($this->enableRegistration) : ?>
                    <a href="http://fabule.com/beta"><?php echo $this->translate('No account? Get invited.'); ?></a>
                <?php endif; ?>
                </div>
                <div class="col-md-6 text-right">
                    <a href="<?php echo $this->url('zfcuser/login') ?>"><?php echo $this->translate('I remember! Sign in.'); ?></a>
                </div>
            </div>
        </div>
    </div>
</div>
